server:
  mode: "debug"
  name: "application"
  port: 8081
  secret: "123"

logger:
  level: "debug"
  filename: "./logs/web_app.log"
  maxSize: 200
  maxAge: 30
  maxBackups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: ""
  dbname: "gin_web"
  maxOpenConns: 100
  maxIdleConns: 200

redis:
  db: 0
  host: "localhost"
  port: 6379
  password: ""
  poolSize: 100
