basePath: /api/v1/
definitions:
  models.Community:
    properties:
      community_id:
        description: 社区 ID
        type: integer
      community_name:
        description: 社区名称
        type: string
      create_time:
        description: 这里是 time.Time 类型，数据库保存的为时间戳类型，如果需要转换，在连接数据库的时候加上 parseTime 参数
        type: string
      introduction:
        description: 社区介绍
        type: string
      update_time:
        description: 更新时间
        type: string
    type: object
  validator.LoginValidator:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  validator.RegisterValidator:
    properties:
      email:
        type: string
      gender:
        type: integer
      password:
        type: string
      re_password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - re_password
    - username
    type: object
host: 127.0.0.1:8081
info:
  contact:
    email: rex_yan@126.com
    name: runsha.yan
    url: http://yanrs.me
  description: Gin Web Project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://yanrs.me
  title: Gin Web
  version: "1.0"
paths:
  /community:
    get:
      consumes:
      - application/json
      description: 获取社区列表接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Community'
            type: array
      security:
      - ApiKeyAuth: []
      summary: 获取社区列表接口
      tags:
      - 社区
  /community/{id}:
    get:
      consumes:
      - application/json
      description: 获取社区详情接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 社区 ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Community'
      security:
      - ApiKeyAuth: []
      summary: 获取社区详情接口
      tags:
      - 社区
  /login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 登录信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/validator.LoginValidator'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 登录
      tags:
      - 认证
  /refreshToken:
    get:
      consumes:
      - application/json
      description: 获取 RefreshToken
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取 RefreshToken
      tags:
      - 认证
  /register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 注册参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/validator.RegisterValidator'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 用户注册
      tags:
      - 认证
swagger: "2.0"
